# Generated by Django 4.2.20 on 2025-03-27 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], max_length=2)),
                ('numero_identificacion', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('telefono_movil', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('numero_radicado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_radicado', models.DateTimeField(auto_now_add=True)),
                ('tipo_radicado', models.CharField(choices=[('P', 'Petición'), ('Q', 'Queja'), ('R', 'Reclamo'), ('S', 'Sugerencia')], max_length=1)),
                ('comentarios', models.TextField()),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pqrs', to='pqrs_app.cliente')),
            ],
        ),
    ]
