# Generated by Django 4.2.20 on 2025-03-27 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(max_length=50)),
                ('numero_identificacion', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('telefono_movil', models.CharField(max_length=15)),
                ('tipo', models.CharField(default='Cliente', max_length=50)),
                ('validacion', models.CharField(default='No', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('numero_radicado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_radicado', models.DateTimeField(auto_now_add=True)),
                ('tipo_radicado', models.CharField(max_length=50)),
                ('comentarios', models.TextField()),
                ('anexo', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pqrs', to='pqrs_app.cliente')),
            ],
        ),
    ]
