# Generated by Django 4.2.20 on 2025-03-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='permisos',
            field=models.CharField(choices=[('A', 'Administrador'), ('C', 'Cliente'), ('G', 'Gestor')], default='C', max_length=2),
        ),
    ]
