# Generated by Django 4.2.1 on 2025-04-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs_app', '0002_alter_cliente_tipo_alter_cliente_tipo_identificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(default=12345, max_length=128),
            preserve_default=False,
        ),
    ]
