# Generated by Django 4.2.1 on 2025-04-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs_app', '0003_cliente_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
    ]
