# Generated by Django 4.2.1 on 2025-04-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs_app', '0004_alter_cliente_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
